### ISSUE TITLE
Can't work well with 1.16.5

### ISSUE THREAD

**Issue by ArchmageTony** [Draylar/fabric-furnaces#28]
Sorry I can't speak English very well,so I use google translate.
In single player game, if i restart game(quit world and login), furnace will lose speed boost and dupe chance.It will become normal furnace.I have to break and place furnace to get it back to speed boost.
***
Mod:
fabric-furnaces-1.3.3-1.16.4
fabric-api-0.29.4+1.16
modmenu-1.14.15

**Comment by srnyx** [comment]
This happens to me too on my server
